spring:
  application:
    name: Questionnaire_sys
  #数据源设置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/questionnaire_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    password: 123456
    username: root
  #redis缓存设置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
#knife4j配置
knife4j:
  enable: true
  production: false
  basic:
    enable: false
server:
  port: 8081
#打开mybatis-plus的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

